Feat/db models
HyperTube-Altair/altair pull request #13
Opened 2024-09-05 10:31 UTC by SpicyI

this Pr:
-implements the DataBase models for Users, comments, subtitles, videos

2024-09-05 15:25 UTC, hmoumani commented on backend/main_app/settings.py
>  SECRET_KEY = "django-insecure-ebwn=qk4lm)p3*l7&qh_+^%8_1c7_i6^n-x1g=_3*dxyqi6#ig"
we definitely should make this an env var ☠️

2024-09-05 15:27 UTC, hmoumani requested changes
GG

2024-09-05 20:57 UTC, SpicyI commented on backend/main_app/settings.py
>  SECRET_KEY = "django-insecure-ebwn=qk4lm)p3*l7&qh_+^%8_1c7_i6^n-x1g=_3*dxyqi6#ig"
but no secrets should be between us 😔

2024-09-06 09:45 UTC, hmoumani commented on backend/main_app/settings.py
>  SECRET_KEY = "django-insecure-ebwn=qk4lm)p3*l7&qh_+^%8_1c7_i6^n-x1g=_3*dxyqi6#ig"
@Hattaki-Hajar

2024-09-07 21:35 UTC, hmoumani approved these changes
GG

2024-09-09 18:16 UTC, Hattaki-Hajar commented on backend/main_app/settings.py
> +DEBUG = os.getenv("Django_DEBUG", "Flase") == "True"
change to "False"

2024-09-09 18:21 UTC, Hattaki-Hajar requested changes
good job

2024-09-09 18:45 UTC, SpicyI commented on backend/main_app/settings.py
> +DEBUG = os.getenv("Django_DEBUG", "Flase") == "True"
nice catch

2024-09-09 18:52 UTC, Hattaki-Hajar approved these changes

2024-09-09 18:52 UTC, merged